# Generated by Django 2.1.5 on 2019-02-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190207_1813'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
